---
title: "R for Data Science (Hadley Wickham) - Chapter 5 Exercises"
output: html_document
---

```{r setup, include=TRUE}
library(tidyverse)
library(nycflights13)
```



## 5.2.4 Exercises
5.2.4 Exercises
Find all flights that

```{r 524, include=TRUE}
# 1
# 1 Had an arrival delay of two or more hours
e <- filter(flights, arr_delay >= 120)
nrow(e)

# 2 Flew to Houston (IAH or HOU)
e <- filter(flights, dest %in% c("HOU","IAH"))
nrow(e)

# 3 Were operated by United, American, or Delta
# From the first rows, I can guess that United's carrier code is UA
#   Not sure what the carrier codes are for Delta and American
#   Do some tricky dplyr from later in chapter to see values

flights %>% count(carrier, sort = TRUE)

# They are DL, AA
e <- filter(flights, carrier %in% c("AA","UA","DL"))
nrow(e)


# 4 Departed in summer (July, August, and September)
e <- filter(flights, between(month,7,9))
nrow(e)

# 5 Arrived more than two hours late, but didn’t leave late
e <- filter(flights, arr_delay > 120 & dep_delay <= 0)
nrow(e)

# 6 Were delayed by at least an hour, but made up over 30 minutes in flight
e <- filter(flights, dep_delay >= 60 & arr_delay < dep_delay - 30)
nrow(e)

# 7 Departed between midnight and 6am (inclusive)
e <- filter(flights, between(hour,0,6))
nrow(e)



# 2
# Another useful dplyr filtering helper is between(). What does it do? Can you use it to simplify the code needed to answer the previous challenges?
# I used it in previous answers already


# 3 
# How many flights have a missing dep_time? What other variables are missing? What might these rows represent?
na_dep_flights <- flights %>% filter(is.na(dep_time))
nrow(na_dep_flights)
na_dep_flights

# These look like canceled flights

# 4
# Why is NA ^ 0 not missing? Why is NA | TRUE not missing? Why is FALSE & NA not missing? Can you figure out the general rule? (NA * 0 is a tricky counterexample!)

# X ^ 0 = 1, even if X is unknown
# TRUE | X is always true, even if X is unknown
# FALSE | X may or may not be true, depending on the value of X, so the expression is unknown



```

## 5.3.1 Exercises


```{r 531, include=TRUE}


# 1 How could you use arrange() to sort all missing values to the start? (Hint: use is.na()).
flights %>% arrange(desc(is.na(dep_time)),hour)

# 2 Sort flights to find the most delayed flights. Find the flights that left earliest.
flights %>% arrange(desc(dep_delay))
flights %>% arrange(dep_delay)

# 3 Sort flights to find the fastest flights.
flights %>% arrange(air_time)

# 4 Which flights travelled the longest? Which travelled the shortest?
flights %>% arrange(distance)
flights %>% arrange(desc(distance))

```

## 5.4.1 Exercises
```{r 541, include=TRUE}

# 1 Brainstorm as many ways as possible to select dep_time, dep_delay, arr_time, and arr_delay from flights.

# 2 What happens if you include the name of a variable multiple times in a select() call?
# duplicates are removed


# 3 What does the one_of() function do? Why might it be helpful in conjunction with this vector?

vars <- c("year", "month", "day", "dep_delay", "arr_delay")

select(flights, one_of(vars))

# one_of() allows you to specify variable names
# You can choose multiple columns that are not in order

# 4 Does the result of running the following code surprise you? How do the select helpers deal with case by default? How can you change that default?

select(flights, contains("TIME"))

# ignores case by default
select(flights, contains("TIME", ignore.case = F))

```

## 5.5.2 Exercises


```{r 552, include=TRUE}

# 1 Currently dep_time and sched_dep_time are convenient to look at, but hard to compute with because they’re not really continuous numbers. Convert them to a more convenient representation of number of minutes since midnight.
t <- (flights %>% 
   mutate(
     hour = dep_time %/% 100,
     minute = dep_time %% 100,
     dep_time = hour * 60 + minute
   )
)
t

# 2 Compare air_time with arr_time - dep_time. What do you expect to see? What do you see? What do you need to do to fix it?

# Note we are using the transformed times below
ggplot(t,aes(arr_time - dep_time, air_time)) + 
  geom_point()

ggplot(t,aes(abs(arr_time - dep_time), air_time)) + 
  geom_point()

# In the first chart, I saw a lot of negative values, which can be solved with abs()
#   Overnight flights will have arr_time < dep_time, causing a negative value
# I also see a bimodal distribution, with no flights in the middle time ranges
# I am guessing this is an artifact of the timezones sometimes being different between locations
# If you fly 3 hours, you either add or lose an hour due to timezone, making the data show either 2 or 4 hours depending on direction
# Timezone issues come later


# 3 Compare dep_time, sched_dep_time, and dep_delay. How would you expect those three numbers to be related?
select(flights, dep_time,sched_dep_time,dep_delay)
# dep_time - sched_dep_time = dep_delay

# 4 Find the 10 most delayed flights using a ranking function. How do you want to handle ties? Carefully read the documentation for min_rank().
flights %>% 
  mutate(delay_rank = min_rank(desc(dep_delay))) %>% 
  filter(delay_rank <= 10) %>% 
  arrange(desc(dep_delay))


# 5 What does 1:3 + 1:12 return? Why?
# longer object length is not a multiple of shorter object length [1]  2  4  6  5  7  9  8 10 12 11
# R tries to replicate the first list until it is the same length
# I'm confused why this is relevant here

# 6 What trigonometric functions does R provide?
?Trig
  
```


## 5.6.7 Exercises
```{r 567, include=TRUE}
# 1 Brainstorm at least 5 different ways to assess the typical delay characteristics of a group of flights. Consider the following scenarios:

# A flight is 15 minutes early 50% of the time, and 15 minutes late 50% of the time.
flights %>% 
  group_by(tailnum) %>% 
  summarise(delay_med = median(arr_delay, na.rm = TRUE)) %>% 
  filter(delay_med > 15)

flights %>% 
  group_by(tailnum) %>% 
  summarise(delay_med = median(arr_delay, na.rm = TRUE)) %>% 
  filter(delay_med < -15)

# A flight is always 10 minutes late.

flights %>% 
  group_by(tailnum) %>% 
  summarise(min_delay = min(arr_delay)) %>% 
  filter(min_delay > 10)

# A flight is 30 minutes early 50% of the time, and 30 minutes late 50% of the time.
flights %>% 
  group_by(tailnum) %>% 
  summarise(delay_med = median(arr_delay, na.rm = TRUE)) %>% 
  filter(delay_med > 30)

flights %>% 
  group_by(tailnum) %>% 
  summarise(delay_med = median(arr_delay, na.rm = TRUE)) %>% 
  filter(delay_med < -30)

# 99% of the time a flight is on time. 1% of the time it’s 2 hours late.

flights %>% 
  group_by(tailnum) %>% 
  # mutate(delay_prank = percentile_rank(arr_delay)) %>% 
  summarise(ontime_rate = mean(arr_delay <= 0, na.rm = TRUE),
            twohrslate_rate  = mean(arr_delay >=120, na.rm = TRUE)) %>% 
  filter(ontime_rate >= 0.99 & twohrslate_rate >= 0.01)

# Which is more important: arrival delay or departure delay?
# arrival delay is more important

# 2 Come up with another approach that will give you the same output as not_cancelled %>% count(dest) and not_cancelled %>% count(tailnum, wt = distance) (without using count()).
not_cancelled <- flights %>% 
  filter(!is.na(dep_delay), !is.na(arr_delay))
# just do mean over a boolean

# 3 Our definition of cancelled flights (is.na(dep_delay) | is.na(arr_delay) ) is slightly suboptimal. Why? Which is the most important column?
# We only care about arr_delay, if the data has a missing value for dep_delay but not in arr_delay, then its probably ok

# 4 Look at the number of cancelled flights per day. Is there a pattern? Is the proportion of cancelled flights related to the average delay?
flights %>% 
  group_by(year, month, day) %>% 
  summarise(cancel_rate = mean(is.na(arr_delay)),
            cancels = sum(is.na(arr_delay)),
            avg_delay = mean(arr_delay,na.rm = TRUE)) %>% 
  ggplot(aes(cancels)) +
    geom_histogram(binwidth = 1)

# Most values are near 0, the histogram is long tailed
flights %>% 
  group_by(year, month, day) %>% 
  summarise(cancel_rate = mean(is.na(arr_delay)),
            cancels = sum(is.na(arr_delay)),
            avg_delay = mean(arr_delay,na.rm = TRUE)) %>% 
  ggplot(aes(cancel_rate,avg_delay)) +
    geom_point()

# Avg. delay and cancel rate are correlated

# 5 Which carrier has the worst delays? Challenge: can you disentangle the effects of bad airports vs. bad carriers? Why/why not? (Hint: think about flights %>% group_by(carrier, dest) %>% summarise(n()))
flights %>% 
  group_by(carrier) %>% 
  summarise(cancel_rate = mean(is.na(arr_delay)),
            cancels = sum(is.na(arr_delay)),
            avg_delay = mean(arr_delay,na.rm = TRUE)) %>% 
  arrange(desc(avg_delay))

# For the challenge, we need to use some stuff from later in the book
# we will compute a z-score for the delay of each flight based on the mean/sd of the dest
# Use relational data, left_join() to attach summary statistics to each record
# Then group by carrier and summarise across those stats

flights %>% 
  group_by(carrier,dest) %>% 
  summarise(n = n(),
            total_delay = sum(arr_delay,na.rm = TRUE))


# I believe this is not possible through dplyr alone
# You need to compute values across both ranges


# 6 What does the sort argument to count() do. When might you use it?
# Sorts output, generally a good idea to see the most common values in a table instead of random ones
  
```

## 5.7.1 Exercises
```{r 571, include=TRUE}
# 1 Refer back to the lists of useful mutate and filtering functions. Describe how each operation changes when you combine it with grouping.

# 2 Which plane (tailnum) has the worst on-time record?

flights %>% 
  group_by(tailnum) %>% 
  summarise(ontime_rate = mean(arr_delay <= 0, na.rm = TRUE),
            n = n()) %>% 
  arrange(ontime_rate, desc(n))

# 3 What time of day should you fly if you want to avoid delays as much as possible?

# 4 For each destination, compute the total minutes of delay. For each, flight, compute the proportion of the total delay for its destination.

flights %>% 
  group_by(dest,tailnum) %>% 
  summarise(total_delay = sum(arr_delay,na.rm = TRUE)) %>%
  group_by(tailnum) %>% 
  mutate(rate_of_dest_delay = total_delay / sum(total_delay))

# 5 Delays are typically temporally correlated: even once the problem that caused the initial delay has been resolved, later flights are delayed to allow earlier flights to leave. Using lag() explore how the delay of a flight is related to the delay of the immediately preceding flight.

flights %>% 
  group_by(origin) %>% 
  transmute(arr_delay,
            last_delay = lag(arr_delay,order = dep_time)) %>% 
  ggplot(aes(last_delay,arr_delay)) +
  geom_point() + 
  geom_smooth()

# There seems to be a very small amount of positive correlation
  

# 6 Look at each destination. Can you find flights that are suspiciously fast? (i.e. flights that represent a potential data entry error). Compute the air time of a flight relative to the shortest flight to that destination. Which flights were most delayed in the air?


# 7 Find all destinations that are flown by at least two carriers. Use that information to rank the carriers.

# 8 For each plane, count the number of flights before the first delay of greater than 1 hour.
```